import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");



export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8FAFC',
  },
  scrollContent: {
    paddingBottom: 40,
  },
  headerButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F1F5F9',
  },
  headerButtonActive: {
    backgroundColor: '#6366F1',
  },
  headerButtonText: {
    color: '#6366F1',
    fontWeight: '600',
    fontSize: 14,
  },
  headerButtonTextActive: {
    color: '#FFFFFF',
  },
  profileHeader: {
    padding: 24,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
  profileImageContainer: {
    position: 'relative',
    marginRight: 16,
  },
  profileImage: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  editImageButton: {
    position: 'absolute',
    bottom: -4,
    right: -4,
    backgroundColor: '#6366F1',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  profileTitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 12,
  },
  ratingVerificationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  ratingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  ratingText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  verificationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  verificationText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '500',
  },
  statsContainer: {
    flexDirection: 'row',
    padding: 16,
    gap: 12,
  },
  statsCard: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 16,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  statsIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  statsValue: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1E293B',
    marginBottom: 4,
  },
  statsLabel: {
    fontSize: 12,
    color: '#64748B',
    textAlign: 'center',
  },
  section: {
    backgroundColor: '#FFFFFF',
    marginHorizontal: 16,
    marginTop:12,
    marginBottom: 16,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1E293B',
    flex: 1,
  },
  addExperienceButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  sectionContent: {
    gap: 16,
  },
  profileField: {
    marginBottom: 16,
  },
  fieldLabel: {
    fontSize: 16,
    fontWeight: '800',
    color: '#374151',
    marginBottom: 6,
  },
  fieldValue: {
    fontSize: 16,
    color: '#1E293B',
    paddingVertical: 8,
    lineHeight: 22,
  },
  fieldInput: {
    fontSize: 16,
    color: '#1E293B',
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
  },
  multilineInput: {
    height: 80,
    textAlignVertical: 'top',
  },
  placeholderText: {
    color: '#94A3B8',
    fontStyle: 'italic',
  },
  skillsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  skillTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#EEF2FF',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    gap: 6,
  },
  skillText: {
    color: '#6366F1',
    fontSize: 14,
    fontWeight: '500',
  },
  removeSkillButton: {
    padding: 2,
  },
  addSkillContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  skillInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 14,
    backgroundColor: '#FFFFFF',
  },
  addSkillButton: {
    backgroundColor: '#6366F1',
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  addSkillButtonDisabled: {
    backgroundColor: '#9CA3AF',
    shadowOpacity: 0,
    elevation: 0,
  },
  noSkillsText: {
    color: '#94A3B8',
    fontStyle: 'italic',
    textAlign: 'center',
    padding: 16,
  },
  // Work Experience Styles
  experienceList: {
    gap: 16,
  },
  experienceItem: {
    borderLeftWidth: 3,
    borderLeftColor: '#6366F1',
    paddingLeft: 16,
    marginLeft: 8,
  },
  experienceContent: {
    backgroundColor: '#F8FAFC',
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  experienceHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  experienceJobTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    flex: 1,
    marginRight: 12,
  },
  experienceActions: {
    flexDirection: 'row',
    gap: 8,
  },
  experienceActionButton: {
    padding: 4,
  },
  experienceCompany: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6366F1',
    marginBottom: 8,
  },
  experienceMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  experienceDuration: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  experienceLength: {
    fontSize: 12,
    color: '#10B981',
    fontWeight: '600',
    backgroundColor: '#D1FAE5',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 8,
  },
  experienceDescription: {
    fontSize: 14,
    color: '#6B7280',
    lineHeight: 20,
  },
  emptyExperience: {
    alignItems: 'center',
    padding: 32,
  },
  emptyExperienceText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#6B7280',
    marginTop: 12,
    marginBottom: 4,
  },
  emptyExperienceSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 20,
  },
  addFirstExperienceButton: {
    marginTop: 16,
    backgroundColor: '#6366F1',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  addFirstExperienceText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  availabilityContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
  },
  availabilityInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  availabilityStatus: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  availabilityText: {
    fontSize: 14,
    color: '#64748B',
  },
  notificationList: {
    gap: 8,
  },
  notificationItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
  },
  notificationInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    flex: 1,
  },
  notificationText: {
    flex: 1,
  },
  notificationLabel: {
    fontSize: 16,
    fontWeight: '500',
    color: '#1E293B',
    marginBottom: 2,
  },
  notificationDescription: {
    fontSize: 14,
    color: '#64748B',
  },
  accountActions: {
    gap: 4,
  },
  accountButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 8,
    borderRadius: 12,
    gap: 12,
  },
  accountButtonText: {
    flex: 1,
    fontSize: 16,
    color: '#1E293B',
    fontWeight: '500',
  },
  logoutButton: {
    marginTop: 8,
    backgroundColor: '#FEF2F2',
  },
  logoutText: {
    color: '#EF4444',
  },
  footer: {
    alignItems: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
  },
  footerText: {
    fontSize: 14,
    color: '#94A3B8',
    textAlign: 'center',
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1E293B',
  },
  modalForm: {
    padding: 20,
  },
  formGroup: {
    marginBottom: 16,
  },
  formRow: {
    flexDirection: 'row',
    gap: 12,
  },
  formGroupHalf: {
    flex: 1,
  },
  formLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 6,
  },
  formInput: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    backgroundColor: '#FFFFFF',
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#D1D5DB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#6366F1',
    borderColor: '#6366F1',
  },
  checkboxLabel: {
    fontSize: 14,
    color: '#374151',
  },
  modalActions: {
    flexDirection: 'row',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    marginBottom:24,
    gap: 12,
  },
  
  saveButton: {
    flex: 2,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: '#6366F1',
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  dateInput: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  borderWidth: 1,
  borderColor: '#D1D5DB',
  borderRadius: 8,
  paddingHorizontal: 12,
  paddingVertical: 10,
  backgroundColor: '#FFFFFF',
},
dateInputDisabled: {
  backgroundColor: '#F3F4F6',
  borderColor: '#E5E7EB',
},
dateInputText: {
  fontSize: 16,
  color: '#1E293B',
},
disabledText: {
  color: '#9CA3AF',
},
availabilityContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  availabilityInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  availabilityBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  availabilityTextContainer: {
    flex: 1,
  },
  availabilityStatus: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 2,
  },
  availabilityDescription: {
    fontSize: 14,
    color: '#64748B',
    marginBottom: 4,
  },
  currentTasksText: {
    fontSize: 12,
    color: '#6366F1',
    fontWeight: '500',
  },

  // Availability Modal Styles
  availabilityOption: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  availabilityOptionSelected: {
    backgroundColor: '#EEF2FF',
    borderColor: '#6366F1',
  },
  availabilityOptionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  availabilityOptionText: {
    flex: 1,
  },
  availabilityOptionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 2,
  },
  availabilityOptionDescription: {
    fontSize: 14,
    color: '#64748B',
  },
  nextAvailableContainer: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  currentTasksContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginTop: 16,
    padding: 12,
    backgroundColor: '#EEF2FF',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#E0E7FF',
  },
  currentTasksInfo: {
    flex: 1,
    fontSize: 14,
    color: '#3730A3',
    marginLeft: 8,
    lineHeight: 18,
  },

  // Modal Styles (enhanced for availability)
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '80%',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1E293B',
  },
  modalSubtitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#374151',
    marginBottom: 16,
    paddingHorizontal: 20,
  },
  modalForm: {
    padding: 20,
  },
  sectionEditButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    gap: 4,
  },
  sectionEditButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6366F1',
  },

 workSamplesContainer: {
  backgroundColor: '#FFFFFF',
  borderRadius: 12,
  padding: 16,
  borderWidth: 1,
  borderColor: '#F1F5F9',
  marginTop: 8,
},
workSamplesContent: {
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
},
workSamplesIconContainer: {
  width: 48,
  height: 48,
  borderRadius: 24,
  backgroundColor: '#EEF2FF',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
workSamplesTextContainer: {
  flex: 1,
},
workSamplesTitle: {
  fontSize: 16,
  fontWeight: '600',
  color: '#1E293B',
  marginBottom: 4,
},
workSamplesDescription: {
  fontSize: 14,
  color: '#64748B',
},
workSamplesPreview: {
  marginTop: 12,
  marginLeft: -4,
},
workSampleThumbnail: {
  width: 80,
  height: 80,
  borderRadius: 8,
  marginHorizontal: 4,
  overflow: 'hidden',
  position: 'relative',
},
workSampleImage: {
  width: '100%',
  height: '100%',
  borderRadius: 8,
},
moreSamplesOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  backgroundColor: 'rgba(0, 0, 0, 0.6)',
  justifyContent: 'center',
  alignItems: 'center',
  borderRadius: 8,
},
moreSamplesText: {
  color: '#FFFFFF',
  fontSize: 16,
  fontWeight: '600',
},
viewAllButton: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingVertical: 4,
  paddingHorizontal: 8,
},
viewAllText: {
  color: '#6366F1',
  fontSize: 14,
  fontWeight: '500',
  marginRight: 2,
},
  viewAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  viewAllText: {
    fontSize: 14,
    color: '#6366F1',
    fontWeight: '500',
    marginRight: 2,
  },
  sectionActionButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionCancelButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#ee4b4bff',
    borderRadius: 6,
    minWidth: 60,
    alignItems: 'center',
  },
  sectionCancelButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFF',
  },
  sectionSaveButton: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#6366F1',
    borderRadius: 6,
    minWidth: 60,
    alignItems: 'center',
  },
  sectionSaveButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
  },

  availabilityHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'flex-start',
  marginBottom: 12,
  paddingHorizontal: 4,
},
availabilityHeaderLeft: {
  flexDirection: 'row',
  alignItems: 'flex-start',
  flex: 1,
},
availabilityIconContainer: {
  width: 40,
  height: 40,
  borderRadius: 20,
  backgroundColor: '#EEF2FF',
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
availabilityHeaderTitle: {
  fontSize: 18,
  fontWeight: '600',
  color: '#1E293B',
  marginBottom: 2,
},
availabilityHeaderSubtitle: {
  fontSize: 14,
  color: '#64748B',
  lineHeight: 18,
},
availabilityEditButton: {
  width: 36,
  height: 36,
  borderRadius: 18,
  backgroundColor: '#F8FAFC',
  justifyContent: 'center',
  alignItems: 'center',
  borderWidth: 1,
  borderColor: '#E2E8F0',
},
availabilityContainer: {
  backgroundColor: '#FFFFFF',
  borderRadius: 16,
  borderWidth: 1,
  borderColor: '#F1F5F9',
  overflow: 'hidden',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.05,
  shadowRadius: 3,
  elevation: 2,
},
availabilityContainerDisabled: {
  opacity: 0.6,
},
availabilityContent: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: 20,
},
availabilityLeft: {
  flexDirection: 'row',
  alignItems: 'center',
  flex: 1,
},
availabilityBadge: {
  width: 48,
  height: 48,
  borderRadius: 24,
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 16,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 4,
  elevation: 3,
},
availabilityTextContainer: {
  flex: 1,
},
availabilityStatus: {
  fontSize: 18,
  fontWeight: '700',
  color: '#1E293B',
  marginBottom: 4,
},
availabilityDescription: {
  fontSize: 14,
  color: '#64748B',
  lineHeight: 18,
  marginBottom: 6,
},
activeTasksContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 4,
},
currentTasksText: {
  fontSize: 13,
  color: '#6366F1',
  fontWeight: '500',
  marginLeft: 6,
},
availabilityRight: {
  marginLeft: 12,
},
availabilityArrow: {
  width: 32,
  height: 32,
  borderRadius: 16,
  backgroundColor: '#F8FAFC',
  justifyContent: 'center',
  alignItems: 'center',
},
availabilityStatusBar: {
  height: 4,
  width: '100%',
  opacity: 0.8,
},

// Header Layout
// Header Layout
profileHeaderContent: {
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 16,
  paddingVertical: 20,
},

// Profile Image Styles
profileImageWrapper: {
  position: 'relative',
},
profileImageContainer: {
  position: 'relative',
},
profileImage: {
  width: 100,
  height: 100,
  borderRadius: 50,
  borderWidth: 3,
  borderColor: '#FFFFFF',
},
editImageButton: {
  position: 'absolute',
  bottom: 0,
  right: 0,
  backgroundColor: '#6366F1',
  borderRadius: 18,
  width: 36,
  height: 36,
  justifyContent: 'center',
  alignItems: 'center',
  borderWidth: 2,
  borderColor: '#1A1F3B',
},
saveImageButton: {
  marginTop: 8,
  backgroundColor: '#6366F1',
  borderRadius: 18,
  paddingHorizontal: 12,
  paddingVertical: 8,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'center',
  gap: 4,
  borderWidth: 2,
  borderColor: '#1A1F3B',
},
saveImageButtonText: {
  color: '#FFFFFF',
  fontSize: 14,
  fontWeight: '600',
},
saveImageButtonDisabled: {
  backgroundColor: '#9CA3AF',
  opacity: 0.6,
},
editIndicator: {
  position: 'absolute',
  top: -5,
  right: -5,
  backgroundColor: '#6366F1',
  borderRadius: 10,
  width: 20,
  height: 20,
  justifyContent: 'center',
  alignItems: 'center',
  borderWidth: 2,
  borderColor: '#1A1F3B',
},

// Profile Info Styles
profileInfo: {
  flex: 1,
  marginLeft: 16,
},
ratingVerificationContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 8,
  gap: 8,
},
// Add these styles to your existing styles
sectionContent: {
  gap: 16,
},
formRow: {
  flexDirection: 'row',
  gap: 12,
},
formGroupHalf: {
  flex: 1,
},
locationSection: {
  gap: 8,
},
locationSectionLabel: {
  fontSize: 14,
  fontWeight: '600',
  color: '#374151',
  marginBottom: 4,
},
locationGrid: {
  flexDirection: 'row',
  flexWrap: 'wrap',
  gap: 8,
},
locationFieldCompact: {
  flex: 1,
  minWidth: '48%', // Two columns
},

// Compact field styles for ProfileField and LocationField components
compactField: {
  marginBottom: 0,
},
compactLabel: {
  fontSize: 12,
  marginBottom: 4,
},
compactInput: {
  fontSize: 14,
  paddingVertical: 10,
  paddingHorizontal: 12,
  minHeight: 44,
},
compactInputMultiline: {
  minHeight: 80,
  textAlignVertical: 'top',
},

// Character count for bio
characterCount: {
  fontSize: 12,
  color: '#6B7280',
  textAlign: 'right',
  marginTop: 4,
},
characterCountWarning: {
  color: '#EF4444',
},
});