import { StyleSheet, Dimensions, Platform } from "react-native";

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
    safeArea: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
    padding: 24,
    justifyContent: 'center',
  },
  header: {
    alignItems: 'center',
    marginBottom: 40,
  },
  logoContainer: {
    width: 100,
    height: 100,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
    position: 'relative',
  },
  logoGradient: {
    width: 100,
    height: 100,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 16,
  },
  logoInnerContainer: {
    width: 92,
    height: 92,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  logoImage: {
    width: 100,
    height: 100,
  },
  logoGlow: {
    position: 'absolute',
    width: 120,
    height: 120,
    borderRadius: 30,
    
    zIndex: -1,
  },
  logoShadow: {
    position: 'absolute',
    width: 110,
    height: 110,
    borderRadius: 27,
    
    zIndex: -2,
  },
  titleContainer: {
    alignItems: 'center',
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    color: '#1C1C1E',
    marginBottom: 8,
    textAlign: 'center',
    letterSpacing: -0.5,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  subtitle: {
    fontSize: 16,
    color: '#8E8E93',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '500',
    maxWidth: 280,
  },
  formContainer: {
    marginBottom: 20,
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#1C1C1E",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  inputWrapper: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E5E5",
    borderRadius: 8,
    backgroundColor: "#FAFAFA",
    paddingHorizontal: 12,
    height: 48,
  },
  inputWrapperFocused: {
    borderColor: "#007AFF",
    backgroundColor: "#FFFFFF",
  },
  inputIcon: {
    marginRight: 8,
  },
  input: {
    flex: 1,
    fontSize: 15,
    color: "#000000",
    fontFamily: Platform.OS === 'ios' ? 'System' : 'Roboto',
    paddingVertical: 0,
  },
  eyeIcon: {
    padding: 4,
    marginLeft: 4,
  },
  passwordRequirements: {
    backgroundColor: "#F8F9FA",
    borderRadius: 6,
    padding: 12,
    marginBottom: 16,
    marginTop: 4,
  },
  requirementsTitle: {
    fontSize: 12,
    fontWeight: "500",
    color: "#666666",
    marginBottom: 8,
  },
  requirementItem: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 4,
  },
  requirementText: {
    marginLeft: 6,
    fontSize: 12,
    color: "#666666",
  },
  requirementMet: {
    color: "#34C759",
  },
 roleSection: {
  marginBottom: 28,
},
roleLabel: {
  fontSize: 13,
  fontWeight: "700",
  color: "#1C1C1E",
  marginBottom: 16,
  letterSpacing: 0.8,
  textTransform: "uppercase",
},
roleContainer: {
  flexDirection: "row",
  backgroundColor: "#F8FAFC",
  borderRadius: 16,
  padding: 4,
  shadowColor: "#000",
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.05,
  shadowRadius: 8,
  elevation: 3,
  borderWidth: 1,
  borderColor: "#F1F5F9",
},
roleOption: {
  flex: 1,
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  paddingVertical: 16,
  paddingHorizontal: 16,
  borderRadius: 12,
  marginHorizontal: 2,
  gap: 8,
  // Smooth transition
  transition: "all 0.3s ease-in-out",
},
roleOptionSelected: {
  backgroundColor: "#FFFFFF",
  shadowColor: "#667eea",
  shadowOffset: { width: 0, height: 4 },
  shadowOpacity: 0.15,
  shadowRadius: 12,
  elevation: 8,
  transform: [{ scale: 1.02 }],
},
roleOptionText: {
  fontSize: 15,
  fontWeight: "600",
  color: "#6B7280",
  marginLeft: 0, // Since we're using gap now
},
roleOptionTextSelected: {
  color: "#667eea",
  fontWeight: "700",
},
// Enhanced icon styling
roleOptionIcon: {
  width: 20,
  height: 20,
  justifyContent: 'center',
  alignItems: 'center',
},
// Optional: Add a subtle animation container
roleOptionInner: {
  flexDirection: "row",
  alignItems: "center",
  justifyContent: "center",
  gap: 8,
},
  signupButton: {
    backgroundColor: "#007AFF",
    borderRadius: 8,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 24,
    shadowColor: "#007AFF",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  signupButtonDisabled: {
    backgroundColor: "#B2D7FF",
    shadowOpacity: 0,
  },
  signupButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "600",
  },
  loginContainer: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  loginText: {
    fontSize: 16,
    color: "#666666",
  },
  loginLink: {
    fontSize: 16,
    color: "#FFFF",
    fontWeight: "600",
    marginLeft: 4,
  },
  signUpGradient: {
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 12,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    marginLeft:5,
  },
  statusMessage: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 12,
    borderRadius: 6,
    marginTop: 8,
    marginBottom: 4,
  },
  statusMessageError: {
    backgroundColor: "#FFE6E6",
  },
  statusMessageSuccess: {
    backgroundColor: "#E6F4EA",
  },
  statusMessageText: {
    marginLeft: 6,
    fontSize: 13,
    fontWeight: "500",
    textAlign: "center",
  },
  statusMessageTextError: {
    color: "#D70000",
  },
  statusMessageTextSuccess: {
    color: "#1E7E34",
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
});

export const colors = {
  primary: "#007AFF",
  success: "#34C759",
  error: "#FF3B30",
  background: "#FFFFFF",
  textPrimary: "#000000",
  textSecondary: "#666666",
  border: "#E5E5E5",
};