import {
  View,
  Text,
  FlatList,
  TextInput,
  TouchableOpacity,
  Image,
  StyleSheet,
  ActivityIndicator,
  KeyboardAvoidingView,
  Linking,
  Platform,
  NativeSyntheticEvent,
  NativeScrollEvent,
  BackHandler,
  Animated,
  Dimensions,
} from 'react-native';

const { width, height } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop:12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#F1F5F9',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0,
    elevation: 0,
    zIndex: 10,
  },
  backButton: {
    padding: 8,
    marginRight: 8,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
  },
  backButtonText: {
    color: '#1F2937',
    fontSize: 16,
    fontWeight: '500',
  },
  chatUserInfo: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatAvatar: {
    position: 'relative',
    marginRight: 12,
  },
  avatarImage: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  avatarPlaceholder: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  avatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  chatOnlineIndicator: {
    position: 'absolute',
    bottom: 2,
    right: 2,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#10B981',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  chatUserDetails: {
    flex: 1,
  },
  chatUserName: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1F2937',
    marginBottom: 2,
  },
  chatJobTitle: {
    fontSize: 14,
    color: '#6366F1',
    fontWeight: '600',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#64748B',
    fontWeight: '500',
  },
  errorText: {
    fontSize: 16,
    color: '#EF4444',
    textAlign: 'center',
    marginTop: 20,
  },
  messagesContent: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  messageContainer: {
    marginBottom: 8,
  },
  myMessage: {
    alignItems: 'flex-end',
  },
  theirMessage: {
    alignItems: 'flex-start',
  },
  messageBubble: {
    maxWidth: '80%',
    padding: 16,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  myBubble: {
    backgroundColor: '#6366F1',
    borderBottomRightRadius: 8,
  },
  theirBubble: {
    backgroundColor: '#F8FAFC',
    borderBottomLeftRadius: 8,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  messageText: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '400',
  },
  myMessageText: {
    color: '#FFFFFF',
  },
  theirMessageText: {
    color: '#1F2937',
  },
  messageFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 6,
  },
  messageTime: {
    fontSize: 12,
    fontWeight: '500',
  },
  myMessageTime: {
    color: 'rgba(255, 255, 255, 0.8)',
  },
  theirMessageTime: {
    color: '#94A3B8',
  },
  seenIcon: {
    marginLeft: 4,
  },
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 40,
    marginTop: height * 0.2,
  },
  emptyStateIcon: {
    marginBottom: 16,
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#6B7280',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateSubtext: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    lineHeight: 20,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    marginBottom:28,
  },
  attachButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F8FAFC',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  attachButtonDisabled: {
    backgroundColor: '#F3F4F6',
  },
  textInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    backgroundColor: '#F8FAFC',
    color: '#1F2937',
    fontWeight: '400',
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
    shadowColor: '#6366F1',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  sendButtonDisabled: {
    backgroundColor: '#D1D5DB',
    shadowOpacity: 0,
    elevation: 0,
  },
  loadingMoreContainer: {
    alignItems: 'center',
    padding: 20,
  },
  loadingMoreText: {
    marginTop: 12,
    fontSize: 14,
    color: '#64748B',
    fontWeight: '500',
  },
  jumpToBottomButton: {
    position: 'absolute',
    bottom: 100,
    alignSelf: 'center',
    backgroundColor: '#6366F1',
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  jumpToBottomContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  jumpToBottomText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  filePreview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  filePreviewContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  fileInfo: {
    flex: 1,
  },
  fileName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 2,
  },
  fileSize: {
    fontSize: 12,
    color: '#6B7280',
  },
  clearButton: {
    padding: 4,
  },
  replyPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F0F9FF',
    borderTopWidth: 1,
    borderTopColor: '#BAE6FD',
  },
  replyPreviewContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  replyInfo: {
    flex: 1,
  },
  replyLabel: {
    fontSize: 12,
    color: '#0369A1',
    fontWeight: '600',
    marginBottom: 2,
  },
  replyText: {
    fontSize: 14,
    color: '#1F2937',
    fontWeight: '500',
  },
  fileUploadProgress: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#F8FAFC',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  uploadContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    gap: 12,
  },
  uploadInfo: {
    flex: 1,
    gap: 6,
  },
  uploadFileName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1F2937',
  },
  uploadStatus: {
    fontSize: 12,
    color: '#6B7280',
  },
  cancelButton: {
    padding: 4,
  },
  typingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 12,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    gap: 4,
    borderWidth: 1,
    borderColor: '#F1F5F9',
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#6366F1',
  },
  typingText: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  replyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
    gap: 6,
  },
  replyText: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '500',
    flex: 1,
  },
  mediaContainer: {
    position: 'relative',
    marginTop: 8,
  },
  media: {
    width: 200,
    height: 150,
    borderRadius: 12,
  },
  mediaOverlay: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    width: 32,
    height: 32,
    borderRadius: 16,
    justifyContent: 'center',
    alignItems: 'center',
  },

// Add these styles to your existing styles file

videoModalContainer: {
  flex: 1,
  backgroundColor: '#000000',
  justifyContent: 'center',
  alignItems: 'center',
},
videoCloseButton: {
  position: 'absolute',
  top: 50,
  left: 20,
  zIndex: 1000,
  backgroundColor: 'rgba(0,0,0,0.5)',
  borderRadius: 20,
  padding: 8,
},
fullScreenVideo: {
  width: '100%',
  height: '100%',
},
videoControls: {
  position: 'absolute',
  bottom: 50,
  left: 0,
  right: 0,
  alignItems: 'center',
},
videoHint: {
  color: '#FFFFFF',
  fontSize: 14,
  opacity: 0.7,
},
videoThumbnailContainer: {
  position: 'relative',
  marginTop: 8,
  borderRadius: 12,
  overflow: 'hidden',
  backgroundColor: '#F3F4F6',
  width: 200,
  height: 150,
},
videoThumbnail: {
  width: '100%',
  height: '100%',
},
playOverlay: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: 'rgba(0,0,0,0.1)',
},
videoBadge: {
  position: 'absolute',
  top: 8,
  right: 8,
  flexDirection: 'row',
  alignItems: 'center',
  backgroundColor: 'rgba(0,0,0,0.7)',
  paddingHorizontal: 6,
  paddingVertical: 3,
  borderRadius: 10,
  gap: 4,
},
badgeText: {
  color: '#fff',
  fontSize: 9,
  fontWeight: '600',
},
documentContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 8,
  padding: 12,
  backgroundColor: '#F8FAFC',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
  maxWidth: 280,
},
documentIcon: {
  width: 48,
  height: 48,
  borderRadius: 8,
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
documentInfo: {
  flex: 1,
},
documentName: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1F2937',
  marginBottom: 4,
},
documentType: {
  fontSize: 12,
  color: '#6B7280',
},
documentDownload: {
  padding: 8,
},
otherFileContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 8,
  padding: 12,
  backgroundColor: '#F8FAFC',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
  maxWidth: 280,
},
otherFileIcon: {
  width: 48,
  height: 48,
  borderRadius: 8,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#F3F4F6',
  marginRight: 12,
},
otherFileInfo: {
  flex: 1,
},
otherFileName: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1F2937',
  marginBottom: 4,
},
otherFileType: {
  fontSize: 12,
  color: '#6B7280',
},
otherFileDownload: {
  padding: 8,
},
videoCloseButton: {
  position: 'absolute',
  top: 50,
  left: 20,
  zIndex: 1000,
  backgroundColor: 'rgba(0,0,0,0.5)',
  borderRadius: 20,
  padding: 8,
},
fullScreenVideo: {
  width: '100%',
  height: '100%',
},
videoControls: {
  position: 'absolute',
  bottom: 50,
  left: 0,
  right: 0,
  alignItems: 'center',
},
videoHint: {
  color: '#FFFFFF',
  fontSize: 14,
  opacity: 0.7,
},
videoThumbnailContainer: {
  position: 'relative',
  marginTop: 8,
  borderRadius: 12,
  overflow: 'hidden',
  backgroundColor: '#F3F4F6',
},
videoThumbnail: {
  width: 200,
  height: 150,
},
videoPlaceholder: {
  width: 200,
  height: 150,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#E5E7EB',
},
videoPlayButton: {
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: [{ translateX: -20 }, { translateY: -20 }],
  width: 40,
  height: 40,
  borderRadius: 20,
  backgroundColor: 'rgba(99, 102, 241, 0.9)',
  justifyContent: 'center',
  alignItems: 'center',
},
videoDurationBadge: {
  position: 'absolute',
  bottom: 8,
  right: 8,
  backgroundColor: 'rgba(0, 0, 0, 0.7)',
  paddingHorizontal: 6,
  paddingVertical: 2,
  borderRadius: 4,
},
videoDurationText: {
  color: '#FFFFFF',
  fontSize: 10,
  fontWeight: '600',
},
documentContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 8,
  padding: 12,
  backgroundColor: '#F8FAFC',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
},
documentIcon: {
  width: 48,
  height: 48,
  borderRadius: 8,
  justifyContent: 'center',
  alignItems: 'center',
  marginRight: 12,
},
documentInfo: {
  flex: 1,
},
documentName: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1F2937',
  marginBottom: 4,
},
documentType: {
  fontSize: 12,
  color: '#6B7280',
},
documentDownload: {
  padding: 8,
},
otherFileContainer: {
  flexDirection: 'row',
  alignItems: 'center',
  marginTop: 8,
  padding: 12,
  backgroundColor: '#F8FAFC',
  borderRadius: 12,
  borderWidth: 1,
  borderColor: '#E5E7EB',
},
otherFileIcon: {
  width: 48,
  height: 48,
  borderRadius: 8,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: '#F3F4F6',
  marginRight: 12,
},
otherFileInfo: {
  flex: 1,
},
otherFileName: {
  fontSize: 14,
  fontWeight: '600',
  color: '#1F2937',
  marginBottom: 4,
},
otherFileType: {
  fontSize: 12,
  color: '#6B7280',
},
otherFileDownload: {
  padding: 8,
},
// Add these styles to your existing styles

// Image Modal Styles
imageModalContainer: {
  flex: 1,
  backgroundColor: '#000000',
},
imageCloseButton: {
  position: 'absolute',
  top: 50,
  right: 20,
  zIndex: 1000,
  backgroundColor: 'rgba(0,0,0,0.5)',
  borderRadius: 20,
  padding: 8,
},
imageScrollContent: {
  flexGrow: 1,
  justifyContent: 'center',
  alignItems: 'center',
},
fullScreenImage: {
  width: '100%',
  height: '100%',
  maxWidth: '100%',
  maxHeight: '100%',
},
imageFileName: {
  position: 'absolute',
  bottom: 50,
  left: 20,
  backgroundColor: 'rgba(0,0,0,0.5)',
  paddingHorizontal: 12,
  paddingVertical: 8,
  borderRadius: 8,
},
imageFileNameText: {
  color: '#FFFFFF',
  fontSize: 14,
},

// Deleted Message Styles
deletedMessageBubble: {
  backgroundColor: '#F3F4F6',
  borderWidth: 1,
  borderColor: '#E5E7EB',
  flexDirection: 'row',
  alignItems: 'center',
  paddingHorizontal: 16,
  paddingVertical: 12,
},
deletedMessageText: {
  fontSize: 14,
  color: '#9CA3AF',
  fontStyle: 'italic',
  marginLeft: 8,
},

actionSheet: {
  position: 'absolute',
  backgroundColor: '#FFFFFF',
  borderRadius: 12,
  top: -30, // Position above the message instead of below
  padding: 4,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 8,
  elevation: 4,
  zIndex: 1000,
  marginTop:12,
  flexDirection: 'row', // Horizontal layout
  alignItems: 'center',
  gap: 4,
},
myActionSheet: {
  right: 0,
},
theirActionSheet: {
  left: 0,
},
actionButton: {
  flexDirection: 'column', // Stack icon and text vertically
  alignItems: 'center',
  paddingVertical: 5,
  paddingHorizontal: 12,
  gap: 4,
  minWidth: 60, // Ensure consistent button size
},
actionText: {
  fontSize: 12, // Smaller text for horizontal layout
  color: '#374151',
  fontWeight: '500',
},
deleteAction: {
  // Remove border for horizontal layout
},
deleteActionText: {
  color: '#EF4444',
},
actionIcon: {
  marginBottom: 2,
},
myReplyContainer: {
  backgroundColor: 'rgba(255, 255, 255, 0.2)',
},
theirReplyContainer: {
  backgroundColor: 'rgba(243, 244, 246, 0.8)',
},
myReplyText: {
  color: 'rgba(255, 255, 255, 0.8)',
},
theirReplyText: {
  color: '#6B7280',
},
myDocumentContainer: {
  backgroundColor: 'rgba(255, 255, 255, 0.1)',
  borderColor: 'rgba(255, 255, 255, 0.2)',
},
theirDocumentContainer: {
  backgroundColor: '#F8FAFC',
  borderColor: '#E5E7EB',
},
myDocumentName: {
  color: '#FFFFFF',
},
theirDocumentName: {
  color: '#1F2937',
},
myDocumentType: {
  color: 'rgba(255, 255, 255, 0.7)',
},
theirDocumentType: {
  color: '#6B7280',
},

myOtherFileContainer: {
  backgroundColor: 'rgba(255, 255, 255, 0.1)',
  borderColor: 'rgba(255, 255, 255, 0.2)',
},
theirOtherFileContainer: {
  backgroundColor: '#F8FAFC',
  borderColor: '#E5E7EB',
},
myOtherFileName: {
  color: '#FFFFFF',
},
theirOtherFileName: {
  color: '#1F2937',
},
myOtherFileType: {
  color: 'rgba(255, 255, 255, 0.7)',
},
theirOtherFileType: {
  color: '#6B7280',
},

 voiceButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FEF2F2',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
  },
  voiceButtonDisabled: {
    backgroundColor: '#F3F4F6',
  },
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0, 0, 0, 0.5)',
  justifyContent: 'flex-end',
},
modalBackdrop: {
  position: 'absolute',
  top: 0,
  left: 0,
  right: 0,
  bottom: 0,
},
modalContent: {
  backgroundColor: '#FFF',
  borderTopLeftRadius: 20,
  borderTopRightRadius: 20,
  overflow: 'hidden',
},
  
});